### ISSUE TITLE
Flathub website visiblity

### ISSUE THREAD

**Issue by nedrichards** [flathub/com.github.ryanakca.slingshot#1]
The build seems to have passed fine: https://flathub.org/builds/#/builders/31/builds/385 but the page on the flathub website isn't populated https://flathub.org/apps/details/com.github.ryanakca.slingshot

My quick script didn't find any obvious issues for the app, but I haven't yet dug into the appstream manually to have a look.

**Comment by barthalion** [comment]
Looks like it started to work at some point during last year!
